### ISSUE TITLE
salaries through lists boss and gang menu

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-management#1]
Hello, I hope to see you soon through this script, Pay salaries through lists boss and gang menu
For example, paying police salaries will pay you from the police safe
And if you are a member of the gang, he pays you from the gang safe
It will be more specialized then

**Comment by ImpulseFPS** [comment]
But make an option between safe salaries or from the server because I know few people that don't want to use paying salaries from gang account/safe
