### ISSUE TITLE
Close menu when too far?

### ISSUE THREAD

**Issue by jimathy** [qbcore-framework/qb-management#10]
The menu closing when you are not near a set location is kinda a downer for people wanting to add it to qb-target locations...

If I add the bossmenu coords into the config, it obviously adds the E to that location, making qb-target pointless
If I add the event to qb-target it automatically closes it. Am I stupid or is the distance check really needed?

I'm trying to work out what I should do for my scripts for others.

**Comment by GhzGarage** [comment]
Feel free to make a config option for target and edit as necessary
