### ISSUE TITLE
[BUG] database sql missing?

### ISSUE THREAD

**Issue by FiZzontje** [qbcore-framework/qb-management#105]

**Comment by perpete1979** [comment]
I 'm sorry you dont give the sql ???

**Comment by DeeRock94** [comment]
I'm sorry @perpete1979 but the documentation suggests:

> ## Installation
> ### Manual
> - Download the script and put it in the `[qb]` directory.
> - IF NEW SERVER: Import `qb-management.sql` in your database
> - IF EXISTING SERVER: Import `qb-management_upgrade.sql` in your database
> - Edit config.lua with coords
> - Restart Script / Server

Regardless if it's a NEW server or an EXISTING server, the `qb-management.sql` doesn't exist on this repo. Which is what @FiZzontje is highlighting. Did you find a solution to this?

**Comment by robertxxiv** [comment]
may i have the sql file ?

**Comment by MaDHouSe79** [comment]
> may i have the sql file ?

```lua
CREATE TABLE IF NOT EXISTS `management_funds` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_name` varchar(50) NOT NULL,
  `amount` int(100) NOT NULL,
  `type` enum('boss','gang') NOT NULL DEFAULT 'boss',
  PRIMARY KEY (`id`),
  UNIQUE KEY `job_name` (`job_name`),
  KEY `type` (`type`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
```

**Comment by MaDHouSe79** [comment]
> -- Use this if you are installing a new DB/Server (these are the default QB-Management jobs/gangs) CREATE TABLE IF NOT EXISTS `management_funds` ( `id` INT(11) NOT NULL AUTO_INCREMENT, `job_name` VARCHAR(50) NOT NULL, `amount` INT(100) NOT NULL, `type` ENUM('boss','gang') NOT NULL DEFAULT 'boss', PRIMARY KEY (`id`), UNIQUE KEY `job_name` (`job_name`), KEY `type` (`type`) );
> 
> INSERT INTO `management_funds` (`job_name`, `amount`, `type`) VALUES ('police', 0, 'boss'), ('ambulance', 0, 'boss'), ('realestate', 0, 'boss'), ('taxi', 0, 'boss'), ('cardealer', 0, 'boss'), ('mechanic', 0, 'boss'), ('lostmc', 0, 'gang'), ('ballas', 0, 'gang'), ('vagos', 0, 'gang'), ('cartel', 0, 'gang'), ('families', 0, 'gang'), ('triads', 0, 'gang');

Thats even better 😄, i don't know why they remove this sql file from this resources.
But on a fress install you mis this in the database and is not added when installing from TxAdmin and you get many errors.
place the file back please cause it's needed for a new install and now you don't have it.

i think if a resource needs a database there sute be a database file in that resources, even if you have an exsisted server.

**Comment by GhzGarage** [comment]
All job/gang accounts are done through the new qb-banking

**Comment by cipher2310** [comment]
the new qb-banking sucks

**Comment by IAmDanielPeter** [comment]
agreed.

**Comment by sabotage93thctv** [comment]
im also trying to find the sqls to replace QBCORE.management_outfits' doesn't exist
