### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jmoneybmk** [qbcore-framework/qb-management#108]
**Describe the bug**
Want to update to the newest qb management because i dont have access to funds in the boss menu.....BUT you guys didnt include the SQL so now im stuck... =/

**To Reproduce**
1. Press 'E' to open the boss menu
2. No option for funds

**Expected behavior**
After opening boss menu i should have access to the funds option that allows me to deposit and withdraw money.

**Screenshots**

![Screenshot 2023-12-12 094209](https://github.com/qbcore-framework/qb-management/assets/153461490/135123cc-ea68-484e-a23d-8896514b0209)
![Screenshot 2023-12-12 094708](https://github.com/qbcore-framework/qb-management/assets/153461490/13a0e50d-91ed-4947-a019-c7a860062664)

**Questions (please complete the following information):**
 - When you last updated: "Installed a brand new server and database today 12/12/2023"
 - Are you using custom resource? which ones? "Plain base qb core server...haven't installed anything but it does use qb-target i supposed."
 - Have you renamed `qb-` to something custom? "No"

**Additional context**
N/A

**Comment by Marky2701** [comment]
Hi, I have the same problem. How did you solve it?

**Comment by Jmoneybmk** [comment]
> Hi, I have the same problem. How did you solve it?

There wasn’t no problem, qb-core updated their stuff so now the society’s account shows up under your bank accounts when you open your bank. They added it to the qb-banking script I believe

**Comment by Marky2701** [comment]
May I ask how does it work? I have looked in the bank and all that and it seems that there isn't the option. Thanks

**Comment by Jmoneybmk** [comment]
Honestly I don’t know…..while I was trying to figure out the issue I went in my server and ran into the bank and seen the police society account there (since I had the job of police) BUT BEFORE THAT major sure your qbcore is up to date
