### ISSUE TITLE
[BUG] - Management / Boss menu not showing up

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-management#111]
**Describe the bug**
I have added vectors for the menu in the QB-Management [cl_config.lua file](https://github.com/qbcore-framework/qb-management/blob/main/client/cl_config.lua) for Bennys (i'm using the Gabz [Benny's](https://fivem.gabzv.com/package/5500605) MLO for this business). I have also added the job correctly to my QB-Core's Shared [jobs.lua](https://github.com/qbcore-framework/qb-core/blob/main/shared/jobs.lua) too, but after restarting my server the menu not showing up at the vector location i have used: vector3(-194.88, -1315.8, 31.3). I am using the E muscle interaction rather than the Third Eye interaction. Please note i am employed as the owner, as you can see i have that role set to 'isboss = true'. I have tried with the other 2 boss roles and still can't get it working

**Expected behaviour**
Menu to appear when walking up to the vector position

**Screenshots**
See screenshots
<img width="1274" alt="cl_config lua" src="https://github.com/qbcore-framework/qb-management/assets/58238399/10f90619-1add-457b-b0c4-064ffd823572">
<img width="934" alt="Screenshot 2023-12-14 162519" src="https://github.com/qbcore-framework/qb-management/assets/58238399/af009a1c-c0e1-4dc7-a496-a18ffd0710c1">
<img width="1143" alt="Screenshot 2023-12-14 162909" src="https://github.com/qbcore-framework/qb-management/assets/58238399/92590925-237b-460a-8089-3f0a33966eb1">

**Questions (please complete the following information):**
 - When you last updated: - Yesterday
 - Are you using custom resource? - No, nothing thats to do with Benny's
 - Have you renamed `qb-` to something custom? - No

**Additional context**
Just not getting the prompt text on screen to say i can open menu by pressing my E keyboard button

**Comment by kyleaitken321** [comment]
@ChlxeThomson did you ever get this to work?

**Comment by ChlxeThomson** [comment]
> @ChlxeThomson did you ever get this to work?

I ended up deleting my server & starting again with the new updated QB framework where they got rid the banking etc

**Comment by kyleaitken321** [comment]
> > @ChlxeThomson did you ever get this to work?
> 
> I ended up deleting my server & starting again with the new updated QB framework where they got rid the banking etc

I tried that making a new server and it still doesn’t seem to work for me

**Comment by ChlxeThomson** [comment]
> 
> 
> 
> 
> 
> 
> > > @ChlxeThomson did you ever get this to work?
> 
> > 
> 
> > I ended up deleting my server & starting again with the new updated QB framework where they got rid the banking etc
> 
> 
> 
> I tried that making a new server and it still doesn’t seem to work for me and still won’t appear 

What isn't working for you?

**Comment by kyleaitken321** [comment]
> > > > @ChlxeThomson did you ever get this to work?
> > 
> > 
> > > 
> > 
> > 
> > > I ended up deleting my server & starting again with the new updated QB framework where they got rid the banking etc
> > 
> > 
> > I tried that making a new server and it still doesn’t seem to work for me and still won’t appear
> 
> What isn't working for you?

The qb-management still doesn’t seem to work

**Comment by Saltineking** [comment]
So I am having this same issue. It's even a fresh install of QB. Does anyone have a fix?
