### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Marky2701** [qbcore-framework/qb-management#113]
**Describe the bug**
Job funds not working even with the new banking and everything, also gang menu not showing up no way.

**To Reproduce**
1. Job menu
2. Funds option not showing up
**Gang**
1. Not showing up even with the name and vector correct, not showing any errors

**Expected behavior**
The funds option in the job menu and the gang menu to open.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Last week
 - Are you using custom resource? which ones?  qb-target
 - Have you renamed `qb-` to something custom?  No

**Additional context**

**Comment by GouveiaXS** [comment]
qb-management dropped money support for whatever reason.

**Comment by Marky2701** [comment]
So how do I make that now I can access the funds?

**Comment by GhzGarage** [comment]
All job/gang accounts are done through the new qb-banking
