### ISSUE TITLE
qb-management still needed? Not in artifact 7290--->

### ISSUE THREAD

**Issue by AntMars008** [qbcore-framework/qb-management#114]
I downloaded artifact 7290 and noticed that qb-management is not present anymore. I know that society money has moved to the new QB-banking, but where is the rest of the management menu? (the hiring/firing and such) I don't want to install qb-management if there is a different way to get to these options. Thanks!

**Comment by AntMars008** [comment]
Sorry, I must be stupid. The QB-management is there, just the SQL is missing. Must I create the table myself?

**Comment by AntMars008** [comment]
OK, I added the SQL from my previous incarnation, but the menu is still not showing up. What am I doing wrong?

**Comment by GhzGarage** [comment]
There is no SQL for qb-management anymore, i think there was an issue here https://github.com/qbcore-framework/qb-banking/issues/124

**Comment by GhzGarage** [comment]
I removed the line, please do the same and you should be good https://github.com/qbcore-framework/qb-banking/commit/aa253b0fec3c95ecdb86fccd3ceae518a701c598

**Comment by AntMars008** [comment]
Working now! Thanks @GhzGarage
