### ISSUE TITLE
[BUG]The boss menu doesn't show manage funds anymore.

### ISSUE THREAD

**Issue by JoshPlne** [qbcore-framework/qb-management#118]
So I use OkOk banking, and recenetly I updated my qb-management. Now none of the societies are syncing. If they make a payment, it doesn't deposit to their fund, and the fund isn't showing in the boss menu anymore. Did something change? And is there a way to revert that? It worked with the old version we had.

**Comment by JoshPlne** [comment]
So, I reverted back to an older version. It works in the sense that you can see the manage funds in the boss menu, however, after 1 restart the money is wiped to zero, even though the database reflects it being there... I'm not sure what changed or why, but this is very bugged at the momeny.

**Comment by JoshPlne** [comment]
You're a legend. All fixed, it is through the banking now, so odd.

**Comment by vlcacek** [comment]
![image](https://github.com/qbcore-framework/qb-management/assets/162354942/afa4f882-651c-45f7-b738-0333b6048219)
help i dont have here money funds
in boss menu

**Comment by vlcacek** [comment]
![image](https://github.com/qbcore-framework/qb-management/assets/162354942/ccb457ea-3071-49d1-b86f-150ee5c4729c)
I have society account in bank i have rank what should i have but i cant deposit or withraw any money

**Comment by Riverdogs009** [comment]
Has there been a fix for OKOKbanking to be used on this new version now or no?
