### ISSUE TITLE
missing export [BUG]

### ISSUE THREAD

**Issue by DNDdjay** [qbcore-framework/qb-management#119]
**Describe the bug**
i was tryet too repair my car with jim mechanic, but the server is saying there is no export for addmoney

 [See error](https://gyazo.com/7685cae676fb0a89f6ddc635b8d96d79)

e.

**Comment by LimaxGG** [comment]
Hi, you just have to update your `qb-banking` and `qb-management` because as of recently all society's are managed through the bank instead.

**Comment by cubacrazy** [comment]
i still have this error..can someone explain how to update it on banks? im using okok banking but cant figure out how to get it working

**Comment by Onlyyashh** [comment]
Im having the same issue, its basically because ps-banking doesnt have exports. So youre probably going to have to change banking systems
