### ISSUE TITLE
[Question] Why two database tables if we combined lua scripts?

### ISSUE THREAD

**Issue by TheDevster** [qbcore-framework/qb-management#12]
Couldn't you have one database table with a field called type (or something) where you can then put boss or gang?  This would reduce the number of tables down because you would not need a separate gangmenu and bossmenu table.

**Comment by ItsANoBrainer** [comment]
Feel free to work on this change and PR it.

**Comment by TheDevster** [comment]
Very well.. PR created.  Please review.  Tested it on my instance and worked without issues.
