### ISSUE TITLE
Gang Boss Menu Exception

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-management#25]
I'm getting the server side exception shown below when changing someone's rank in the Gang Boss menu.

![image](https://user-images.githubusercontent.com/43043270/158904570-eb069970-db80-4f06-bc31-484886742cf0.png)

**Comment by ItsANoBrainer** [comment]
Look at the PRs, theres a fix pending already.
https://github.com/qbcore-framework/qb-management/pull/20
