### ISSUE TITLE
Being Paid from the Society fund

### ISSUE THREAD

**Issue by TheCrypticOG** [qbcore-framework/qb-management#31]
Right now to be paid from the society fund of each job it calls this export

local account = exports['qb-bossmenu']:GetAccount(Player.PlayerData.job.name)
TriggerEvent('qb-bossmenu:server:removeAccountMoney', Player.PlayerData.job.name, payment)

I was wondering if these have been replaced yet as I did not see anything in the readme about it

**Comment by ItsANoBrainer** [comment]
Hi @erikmeyer08, this hasn't been added to the main recipe yet which is why the other resources haven't been updated for it. For now just change it manually and we should be adapting this to all the other resources soon. Let me know if you have any other questions. Thank you for the information.

**Comment by ItsANoBrainer** [comment]
Fixed here:
https://github.com/qbcore-framework/qb-management/pull/37

You still require changing the export yourself manually wherever it exists.
