### ISSUE TITLE
DrawText

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-management#34]
![image](https://user-images.githubusercontent.com/43043270/159107496-61e46591-6763-49ee-a365-82b0a80906d8.png)

**Comment by ItsANoBrainer** [comment]
Hi @erikmeyer08 this resource requires the dev branch of qb-core that has this new feature. This information will be added to the readme, but the dev branch should be merged to main soon.

**Comment by erikmeyer08** [comment]
Thanks!
Soon as in like this week? I'll see If I can download it.

Also I think the message and position are backwards in the cl_boss and cl_gang files.
exports['qb-core']:DrawText('left', '[E] Open Gang Management')
![image](https://user-images.githubusercontent.com/43043270/159107991-96a41df3-91d3-43ec-9c01-85fb202eaac8.png)

**Comment by ItsANoBrainer** [comment]
Fixing this now, thanks for the report. A lot of small things needed fixing with this, it's not my night!

**Comment by ItsANoBrainer** [comment]
Also yes dev branch should be merged into live on Sunday (hopefully). We are waiting for the rest of the resources that require it to be finished and then we are pushing them all together. The dev build is stable and thoroughly tested and reviewed. Its ready for live merge. (Manual change still needed to the exports listed here https://github.com/qbcore-framework/qb-management/issues/31 until this is apart of the main recipe)

**Comment by erikmeyer08** [comment]
lol no worries.

Ok, thanks for the update!
