### ISSUE TITLE
qb-bossmenu:server:addAccountMoney

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-management#36]
The event "qb-bossmenu:server:addAccountMoney" is not in this latest update. Its required for billing from qb-phone.

TriggerEvent("qb-bossmenu:server:addAccountMoney", society, amount)

**Comment by ItsANoBrainer** [comment]
Fixed with https://github.com/qbcore-framework/qb-management/pull/37.

Thank you for the report.
