### ISSUE TITLE
[BUG] No such export DrawExport in resource qb-core

### ISSUE THREAD

**Issue by masutto** [qbcore-framework/qb-management#38]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

Hey All, I followed the instructions to the "T" when installing this script and i edited my cl_config for the coords and saved it, restarted the server and i then get this error 
![qb-management error](https://user-images.githubusercontent.com/28587596/159344620-9299e6e6-f7e8-4e09-b677-e59f3a48d166.PNG)

I have cleared my server cache, updated all the dependencies to the latest and im still facing this issue.

**Comment by menkzy** [comment]
Not a bug, you need to update your qb-core to the dev build.

**Comment by masutto** [comment]
> menkzy

I have i went to qb-core repository and clicked on code then download zip. Not sure if this is the one your referring too?

I did try this though in cl_boss.lua line 8 changed the follwoing:
Ln 008: exports['qb-core']:HideText() to exports['qb-drawtext']:HideText()

Ln 316:  exports['qb-core']:DrawText('Open Job Management', 'left') to  exports['qb-drawtext']:DrawText('Open Job Management', 'left')

Ln 320:  exports['qb-core']:HideText() to  exports['qb-drawtext']:HideText()

Cl_gang:

Ln 8: same as above
Ln 318: Same as above
Ln 322: same as above

Seems to fix this issue

**Comment by realSixGrams** [comment]
https://github.com/IdrisDose/qb-drawtext

Use this, and change exports['qb-core'] to exports['qb-drawtext']

**Comment by masutto** [comment]
i did, i submitted 2 pull request earlier with the changes. this is what fixed it
