### ISSUE TITLE
[BUG] Co-Owner can demote and fire owner in bossmenu, Co-Owner can also promote himself to Owner of the job.

### ISSUE THREAD

**Issue by opticny** [qbcore-framework/qb-management#43]
**Describe the bug**
Lower ranks with access to boss menu can promote their self to a higher rank, they can also fire and demote higher ranks above them.

**To Reproduce**
1. Go to the bossmenu location of any job.
2. Set your job to the lowest rank with access to bossmenu.
3. Try to promote yourself to the highest rank; if there is anyone else with the same job with a grade higher than you try to demote and fire them.

**Expected behavior**
I would except it to make a log looking like this and not promote/demote/fire anyone: https://prnt.sc/mNpmjkoJBTES

**Questions (please complete the following information):**
 - When you last updated: Two weeks ago
 - Have you renamed `qb-` to something custom? No

**Comment by ItsANoBrainer** [comment]
Ill take a look at this implementation when I get some time, thanks.

**Comment by opticny** [comment]
accidentally closed issue, sorry!

**Comment by GhzGarage** [comment]
@opticny Can you test his PR ^^
