### ISSUE TITLE
[BUG] gang members doesn't have access to gang menu

### ISSUE THREAD

**Issue by SKITTLE6969** [qbcore-framework/qb-management#46]
**Describe the bug**
gang members doesn't have access to gang menu only boss can access

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by nullvariable** [comment]
this is not a bug, currently it is only intended for players with the `isboss` flag to be able to access the gang/boss menus.

**Comment by Rtextbook** [comment]
i just want to know how i can have qb target work with this. it works fine when setr target to false. but i want to use target and then they stop showing up .

**Comment by SKITTLE6969** [comment]
closing
