### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by viridcupid50** [qbcore-framework/qb-management#49]
money not going into society bank after sending an invoice as a boss of mechanic or any other job

**Comment by nullvariable** [comment]
hello @viridcupid50 can you give a more specific set of steps where this is happening for you?
Also if you could confirm that you are running the latest version of the resources in question that will help isolate the issue.

**Comment by LightUpFam** [comment]
same is there an export im suppose to use if a job is looking for a bossmenu society

**Comment by nullvariable** [comment]
have a look at this issue and see if that helps
https://github.com/qbcore-framework/qb-management/issues/56#issuecomment-1146594865
