### ISSUE TITLE
Error: qb-management

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-management#5]
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: qb-management was unable to execute a query!
[      script:oxmysql]     Table 'server-1.bossmenu' doesn't exist
[      script:oxmysql]     SELECT * FROM bossmenu
[      script:oxmysql] > query_default (@oxmysql/dist/server/build.js:16103)
[      script:oxmysql] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Mobius1** [comment]
It's telling you the table that gets created when importing the SQL file is missing. Did you import the SQL file?

**Comment by Andyauk** [comment]
> It's telling you the table that gets created when importing the SQL file is missing. Did you import the SQL file?

ah ok. it doesnt use the old bossmenu sql
