### ISSUE TITLE
[BUG] Bossmenu Bug

### ISSUE THREAD

**Issue by GhostV-Survival** [qbcore-framework/qb-management#53]
When you gave a Grade in jobs.lua isboss = true only the highest grad can access the bossmenu

**Comment by nullvariable** [comment]
hello @GhostLegionRP can you share an example of the config/code you're using?

**Comment by GhostLegionRP** [comment]
> hello @GhostLegionRP can you share an example of the config/code you're using?

This is my jobs.lua

`QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	['unemployed'] = {
		label = 'Civilian',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Freelancer',
                payment = 10
            },
        },
	},
    ['planepilot'] = {
        label = 'Delivery',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = {
                name = 'Pilot',
                payment = 250
            },
        },
    },
	['police'] = {
		label = 'Police Department',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Kadett',
                payment = 625
            },
			['1'] = {
                name = 'Officer',
                payment = 875
            },
			['2'] = {
                name = 'Detective',
                payment = 1000
            },
			['3'] = {
                name = 'Sergeant',
                payment = 1250
            },
			['4'] = {
                name = 'Lieutenant',
                payment = 1500
            },
			['5'] = {
                name = 'Captain',
				isboss = true,
                payment = 1875
            },
			['6'] = {
                name = 'Chief',
				isboss = true,
                payment = 2125
            },
        },
	},
	['ambulance'] = {
		label = 'Rettungsdienst',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Student Vorklinik',
                payment = 50
            },
			['1'] = {
                name = 'Student Klinik',
                payment = 75
            },
			['2'] = {
                name = 'Notarzt',
                payment = 100
            },
			['3'] = {
                name = 'Facharzt',
                payment = 125
            },
			['4'] = {
                name = 'Oberarzt',
                payment = 150
            },
			['5'] = {
                name = 'Leitender Oberarzt',
				isboss = true,
                payment = 150
            },
			['6'] = {
                name = 'Ärztlicher Direktor',
				isboss = true,
                payment = 150
            },
        },
	},
	['realestate'] = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = {
                name = 'Manager',
				isboss = true,
                payment = 150
            },
        },
	},
	['taxi'] = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Recruit',
                payment = 50
            },
			['1'] = {
                name = 'Driver',
                payment = 75
            },
			['2'] = {
                name = 'Event Driver',
                payment = 100
            },
			['3'] = {
                name = 'Sales',
                payment = 125
            },
			['4'] = {
                name = 'Manager',
				isboss = true,
                payment = 150
            },
        },
	},
    ['bus'] = {
		label = 'Bus',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Driver',
                payment = 50
            },
		},
	},
	['cardealer'] = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Recruit',
                payment = 50
            },
			['1'] = {
                name = 'Showroom Sales',
                payment = 75
            },
			['2'] = {
                name = 'Business Sales',
                payment = 100
            },
			['3'] = {
                name = 'Finance',
                payment = 125
            },
			['4'] = {
                name = 'Manager',
				isboss = true,
                payment = 150
            },
        },
	},
	['mechanic'] = {
		label = 'Mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Recruit',
                payment = 50
            },
			['1'] = {
                name = 'Novice',
                payment = 75
            },
			['2'] = {
                name = 'Experienced',
                payment = 100
            },
			['3'] = {
                name = 'Advanced',
                payment = 125
            },
			['4'] = {
                name = 'Manager',
				isboss = true,
                payment = 150
            },
        },
	},
	['judge'] = {
		label = 'Honorary',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Judge',
                payment = 100
            },
        },
	},
	['lawyer'] = {
		label = 'Law Firm',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Associate',
                payment = 50
            },
        },
	},
	['reporter'] = {
		label = 'Reporter',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Journalist',
                payment = 50
            },
        },
	},
	['trucker'] = {
		label = 'Trucker',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Driver',
                payment = 50
            },
        },
	},
	['tow'] = {
		label = 'Towing',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Driver',
                payment = 50
            },
        },
	},
	['garbage'] = {
		label = 'Garbage',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Collector',
                payment = 50
            },
        },
	},
	['vineyard'] = {
		label = 'Vineyard',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Picker',
                payment = 50
            },
        },
	},
	['hotdog'] = {
		label = 'Hotdog',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Sales',
                payment = 50
            },
        },
	},
    ['homeland'] = {
		label = 'Homeland',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Azubi',
                payment = 250
            },
			['1'] = {
                name = 'Bürgermeister',
                payment = 2125
            },
			['2'] = {
                name = 'Agent',
                payment = 1000
            },
			['3'] = {
                name = 'Special Agent',
                payment = 1250
            },
            ['4'] = {
                name = 'Minister',
                isboss = true,
                payment = 2500
            },
            ['5'] = {
                name = 'Vize Gouverneur',
				isboss = true,
                payment = 2500
            },
            ['6'] = {
                name = 'Gouverneur',
                isboss = true,
                payment = 2500
            },
        },
	},
    ['homeland_sec'] = {
		label = 'Homeland Security',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = {
                name = 'Nomad',
                payment = 750
            },
			['1'] = {
                name = 'Private',
                payment = 1125
            },
			['2'] = {
                name = 'Sergeant',
                payment = 1500
            },
			['3'] = {
                name = 'Lieutenant',
                payment = 1625
            },
            ['4'] = {
                name = 'Major',
                payment = 1750
            },
            ['5'] = {
                name = 'General',
				isboss = true,
                payment = 2000
            },
            ['6'] = {
                name = 'Commander',
				isboss = true,
                payment = 2250
            },
        },
	},
}

            -- Jobs Creator integration (jobs_creator)
            RegisterNetEvent("jobs_creator:injectJobs", function(jobs)
                QBShared.Jobs = jobs
            end)
        `

**Comment by GhostLegionRP** [comment]
@nullvariable ?

**Comment by GhostLegionRP** [comment]
ok the problem is opnly when you have more the 2 `isBoss = true`

**Comment by nzkfc** [comment]
> hello @GhostLegionRP can you share an example of the config/code you're using?

Can confirm if you have more then 1 rank as isboss it bugs out.

**Comment by GhostLegionRP** [comment]
Whats with the BUg we already have this issue?
