### ISSUE TITLE
[BUG] issue with menu staying on screen

### ISSUE THREAD

**Issue by FrequencyRoleplay** [qbcore-framework/qb-management#59]
when you go next to your gang/boss menu  and walk away the :[E] open menu stays on the screen and doesnt go away no matter how far you get from it

**Comment by Jamesmayl** [comment]
Replicated it, and nothing is wrong with it.

**Comment by Jamesmayl** [comment]
Can you send a screenshot? I replicated it and the [E] open menu went away. @LightUpFam

**Comment by sinphoenix** [comment]
this issue still on going?

**Comment by Pockettx** [comment]
Still an issue. It happens mostly for us with gang menus and it's when you walk by the menu so the option to open shows up, but you keep walking by, when out of range the option to open the boss menu never goes away until you go back and go into the menu.
