### ISSUE TITLE
Boss Menu Won't Show Up

### ISSUE THREAD

**Issue by DarthVaderz1996** [qbcore-framework/qb-management#61]
**Describe the bug**
I have a problem where no boss menus will show for the person who is boss. everything start with no errors and i have added it to sql.

**Comment by ChickenDipper1** [comment]
I have this same issue, any advice?

**Comment by Rtextbook** [comment]
i want to know how to get qb target to work \with it.

**Comment by sinphoenix** [comment]
Make sure you have Target set to true in config
