### ISSUE TITLE
[BUG] I cant put gang menu to work!

### ISSUE THREAD

**Issue by NFMj** [qbcore-framework/qb-management#62]
in fivem give thie erro when i start the scrip:
![Capturar](https://user-images.githubusercontent.com/91223136/178751502-8cd2548c-4d2b-4fa6-af9b-c5a092c8fc0b.PNG)
And the erro is in this line of code:
![Capturar2](https://user-images.githubusercontent.com/91223136/178751669-9e95635d-2c4a-44b4-a0ee-338340b52a2b.PNG)
Any idea how to fix this?
Best regards.

**Comment by tom-osborne** [comment]
What do you have in your `Config.GangMenus`?

**Comment by Jamesmayl** [comment]
@NFMj Please read the above and get back to us. ^^^
