### ISSUE TITLE
[BUG] Employee Menu Problem because of LIKE in SQL

### ISSUE THREAD

**Issue by GhostV-Survival** [qbcore-framework/qb-management#64]
Hey, i have 2 jobs one is called 'mechanic' the other 'mechanic_lost' if i now look at 'mechanic' at the management of employees in the boss menu i also see the employees of 'mechanic_lost' but if i look at 'mechanic_lost' at the employees i also only see the employees there. i strongly suspect it's the database query in qb-management [local players = MySQL.query.await("SELECT * FROM players WHERE job LIKE '%".. jobname .."%'", {})], is there any way to modify this so that it directly addresses the jobname with 100% match?

JobID: mechanic
![image](https://user-images.githubusercontent.com/100316482/179608493-8b2b8459-570e-4c71-af92-49d622df925b.png)

JobID: mechanic_lost
![image](https://user-images.githubusercontent.com/100316482/179608753-696cd703-85c2-4804-bfee-d77dfba78db2.png)

**Comment by brynnie1** [comment]
Ye I have this same issue, hopefully the guys will be able to fix this

**Comment by nzkfc** [comment]
I know it's not a fix, but why not name jobs based on the business name rather then similar to mechanic? For example we have "bennys" "jinx" and "whenua" because that is the company name e.g. Jinx Motorsports and Paint etc

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-management/pull/66
