### ISSUE TITLE
HOW DO YOU OPEN?

### ISSUE THREAD

**Issue by xxUnknown13xx** [qbcore-framework/qb-management#70]
How do i open it? I tried everything. is there another commands? beside /bossmenu /qbmanagement /qbmenu /qbmanagement?

**Comment by streetzoom** [comment]
Go to qb-management/client/cl_config.lua There is Config.BossMenus with locations for a different jobs. You can /tp to it and check if it works.
![image](https://user-images.githubusercontent.com/57523347/227715958-2285dba4-7c7b-4c9a-8255-18cc5462ff3a.png)
