### ISSUE TITLE
[BUG] Cannot open boss menu

### ISSUE THREAD

**Issue by Soldierofthelam** [qbcore-framework/qb-management#75]
I'm not sure what's going on with this new qb-management system but boss menu will not open,

"Update"
Figured out why bossmenu not showing. they used the vectors for the location on custom mlo's and not the default map.
 
 Almost all the boss locations are not set to default locations which makes it a pain if you want qb-target turned on,
Why in the hell wouldn't the vectors be setup for default  map locations and not custom maps not provided? some of the custom mlo that is being used is paid mlo's.

 I'm not closing this out even though it's not a bug because the scripter never mentions anywhere that you need custom mlo's to find the boss menu.

the way I found the bossmenu is I went into noclip mode then use the vector to tp from the /tp cords and sure enough over more than half the bossmenu is hidden in default building above or below ground.

 Under the qbcore/shared/locations folder they have actually listed the custom Mlo's that has some of the bossmenu placed at
And under qb-management/client/custom shows the vectors for these custom mlo.

 Luckily for me I have the custom mlo's and the locations folder did help me know which ones to install, However this is a very serious issue for people who don't mess with visual studio or codes. Esp when no guidance was provided from the script makers about these and other issues.

"As it stands this is not a working basic server setup with half of the scripts you need for a functional server based off of custom mlo's"

example of finding bossmenu under mechanic job with fresh install of Qbcore server with TXadmin recipe.
https://imgur.com/vvay6iZ
https://imgur.com/91y36Nr

 -- Unknown/Random/Vanilla
    ['burgershot'] = vector4(-1199.0568, -882.4495, 13.3500, 209.1105),
    ['casino'] = vector4(923.2289, 47.3113, 81.1063, 237.6052),

    -- Gabz
    ['arcade'] = vector4(-1649.6089, -1083.9313, 13.1575, 46.4121),
    ['beanmachinelegion'] = vector4(116.16, -1022.99, 29.3, 0.0),
    ['bowling'] = vector4(761.5008, -777.7256, 26.3078, 90.5581),
    ['pizzaria'] = vector4(790.4561, -758.4601, 26.7424, 270.2329),
    ['catcafe'] = vector4(-580.8388, -1072.7872, 22.3296, 359.0078),
    ['carmeet'] = vector4(958.8237, -1699.6659, 29.5574, 71.2731),
    ['davispd'] = vector4(382.5791, -1591.1827, 29.2828, 145.0991),
    ['popsdiner'] = vector4(1595.9753, 6448.6421, 25.3170, 28.3026),
    ['davisfirestation'] = vector4(216.7576, -1638.3801, 29.5151, 137.8174),
    ['harmony'] = vector4(1183.0693, 2648.5313, 37.8363, 194.0603),
    ['haters'] = vector4(-1117.1525, -1439.4297, 5.1075, 103.4411),
    ['hayes'] = vector4(-1435.7040, -445.7360, 35.5964, 220.1762),
    ['pdm'] = vector4(-48.2113, -1105.4769, 27.2634, 339.5899),
    ['bennys'] = vector4(-47.5289, -1042.6086, 28.3532, 247.9748),
    ['impound'] = vector4(-190.5874, -1156.1343, 23.0482, 158.9385),
    ['lamesaauto'] = vector4(720.4776, -1092.1934, 22.2866, 310.1469),
    ['lamesapd'] = vector4(824.3735, -1290.0670, 28.2364, 266.1293),
    ['lostmc'] = vector4(982.6339, -104.7095, 74.8488, 30.8738),
    ['pillbox'] = vector4(298.1153, -584.2825, 43.2609, 252.7553),
    ['mrpd'] = vector4(432.0686, -981.6853, 30.7119, 267.3501),
    ['mirrorparkhouse1'] = vector4(945.9535, -652.9119, 58.0228, 90.5541),
    ['pacificbank'] = vector4(229.9529, 214.3890, 105.5561, 294.6791),
    ['paletoliquor'] = vector4(-154.2287, 6328.8682, 31.5665, 133.1992),
    ['paletopd'] = vector4(-436.0935, 6015.2026, 31.4892, 132.9752),
    ['paletogasstation'] = vector4(120.2420, 6625.4722, 31.9580, 36.5687),
    ['pinkcage'] = vector4(323.9055, -203.2524, 54.0866, 186.8505),
    ['ponsonbys1'] = vector4(-165.2497, -304.3988, 38.07126, 0.0),
    ['ponsonbys2'] = vector4(-1448.1, -236.8420, 48.15098, 0.0),
    ['ponsonbys3'] = vector4(-709.8120, -150.6267, 35.75312, 0.0),
    ['prison'] = vector4(1847.1284, 2586.0696, 45.6726, 91.7828),
    ['rangerstation'] = vector4(387.3204, 790.1508, 187.6927, 4.7656),
    ['recordastudio'] = vector4(473.3006, -109.4360, 62.7418, 350.8488),
    ['sandypd'] = vector4(1839.7510, 3667.9907, 33.8787, 29.1744),
    ['suburban1'] = vector4(124.9756, -217.6290, 55.81879, 0.0),
    ['suburban2'] = vector4(617.4776, 2757.4810, 43.34935, 0.0),
    ['suburban3'] = vector4(-1195.8690, -773.5746, 18.58485, 0.0),
    ['suburban4'] = vector4(-3170.9670, 1049.9310, 22.12445, 0.0),
    ['triadrecords'] = vector4(-829.0061, -698.2049, 28.0583, 291.2052),
    ['tuner'] = vector4(157.5888, -3017.9968, 7.0400, 94.0695),
    ['vu'] = vector4(129.4555, -1299.6754, 29.2327, 27.6378),

    -- Patoche
    ['luxerydealership'] = vector4(-1273.22, -371.11, 36.64, 301.8),

    -- Unclejust
    ['digitalden'] = vector4(-656.28, -849.92, 24.51, 167.42),
    ['ifruitstore1'] = vector4(-646.78, -288.17, 35.49, 297.73),
    ['ifruitstore2'] = vector4(-778.7451, -598.2717, 30.2772, 181.0197),
    ['taxijob'] = vector4(908.7, -166.45, 74.13, 54.88),
    ['vineyard'] = vector4(-1892.29, 2038.47, 140.86, 339.23),
    ['weazelnews'] = vector4(-604.82, -933.22, 23.86, 292.3),
}

**Comment by Andyauk** [comment]
> I'm not sure what's going on with this new qb-management system but boss menu will not open,
> 
> "Update" Figured out why bossmenu not showing. they used the vectors for the location on custom mlo's and not the default map.
> 
> Almost all the boss locations are not set to default locations which makes it a pain if you want qb-target turned on, Why in the hell wouldn't the vectors be setup for default map locations and not custom maps not provided? some of the custom mlo that is being used is paid mlo's.
> 
> I'm not closing this out even though it's not a bug because the scripter never mentions anywhere that you need custom mlo's to find the boss menu.
> 
> the way I found the bossmenu is I went into noclip mode then use the vector to tp from the /tp cords and sure enough over more than half the bossmenu is hidden in default building above or below ground.
> 
> Under the qbcore/shared/locations folder they have actually listed the custom Mlo's that has some of the bossmenu placed at And under qb-management/client/custom shows the vectors for these custom mlo.
> 
> Luckily for me I have the custom mlo's and the locations folder did help me know which ones to install, However this is a very serious issue for people who don't mess with visual studio or codes. Esp when no guidance was provided from the script makers about these and other issues.
> 
> "As it stands this is not a working basic server setup with half of the scripts you need for a functional server based off of custom mlo's"
> 
> example of finding bossmenu under mechanic job with fresh install of Qbcore server with TXadmin recipe. https://imgur.com/vvay6iZ https://imgur.com/91y36Nr
> 
> -- Unknown/Random/Vanilla ['burgershot'] = vector4(-1199.0568, -882.4495, 13.3500, 209.1105), ['casino'] = vector4(923.2289, 47.3113, 81.1063, 237.6052),
> 
> ```
> -- Gabz
> ['arcade'] = vector4(-1649.6089, -1083.9313, 13.1575, 46.4121),
> ['beanmachinelegion'] = vector4(116.16, -1022.99, 29.3, 0.0),
> ['bowling'] = vector4(761.5008, -777.7256, 26.3078, 90.5581),
> ['pizzaria'] = vector4(790.4561, -758.4601, 26.7424, 270.2329),
> ['catcafe'] = vector4(-580.8388, -1072.7872, 22.3296, 359.0078),
> ['carmeet'] = vector4(958.8237, -1699.6659, 29.5574, 71.2731),
> ['davispd'] = vector4(382.5791, -1591.1827, 29.2828, 145.0991),
> ['popsdiner'] = vector4(1595.9753, 6448.6421, 25.3170, 28.3026),
> ['davisfirestation'] = vector4(216.7576, -1638.3801, 29.5151, 137.8174),
> ['harmony'] = vector4(1183.0693, 2648.5313, 37.8363, 194.0603),
> ['haters'] = vector4(-1117.1525, -1439.4297, 5.1075, 103.4411),
> ['hayes'] = vector4(-1435.7040, -445.7360, 35.5964, 220.1762),
> ['pdm'] = vector4(-48.2113, -1105.4769, 27.2634, 339.5899),
> ['bennys'] = vector4(-47.5289, -1042.6086, 28.3532, 247.9748),
> ['impound'] = vector4(-190.5874, -1156.1343, 23.0482, 158.9385),
> ['lamesaauto'] = vector4(720.4776, -1092.1934, 22.2866, 310.1469),
> ['lamesapd'] = vector4(824.3735, -1290.0670, 28.2364, 266.1293),
> ['lostmc'] = vector4(982.6339, -104.7095, 74.8488, 30.8738),
> ['pillbox'] = vector4(298.1153, -584.2825, 43.2609, 252.7553),
> ['mrpd'] = vector4(432.0686, -981.6853, 30.7119, 267.3501),
> ['mirrorparkhouse1'] = vector4(945.9535, -652.9119, 58.0228, 90.5541),
> ['pacificbank'] = vector4(229.9529, 214.3890, 105.5561, 294.6791),
> ['paletoliquor'] = vector4(-154.2287, 6328.8682, 31.5665, 133.1992),
> ['paletopd'] = vector4(-436.0935, 6015.2026, 31.4892, 132.9752),
> ['paletogasstation'] = vector4(120.2420, 6625.4722, 31.9580, 36.5687),
> ['pinkcage'] = vector4(323.9055, -203.2524, 54.0866, 186.8505),
> ['ponsonbys1'] = vector4(-165.2497, -304.3988, 38.07126, 0.0),
> ['ponsonbys2'] = vector4(-1448.1, -236.8420, 48.15098, 0.0),
> ['ponsonbys3'] = vector4(-709.8120, -150.6267, 35.75312, 0.0),
> ['prison'] = vector4(1847.1284, 2586.0696, 45.6726, 91.7828),
> ['rangerstation'] = vector4(387.3204, 790.1508, 187.6927, 4.7656),
> ['recordastudio'] = vector4(473.3006, -109.4360, 62.7418, 350.8488),
> ['sandypd'] = vector4(1839.7510, 3667.9907, 33.8787, 29.1744),
> ['suburban1'] = vector4(124.9756, -217.6290, 55.81879, 0.0),
> ['suburban2'] = vector4(617.4776, 2757.4810, 43.34935, 0.0),
> ['suburban3'] = vector4(-1195.8690, -773.5746, 18.58485, 0.0),
> ['suburban4'] = vector4(-3170.9670, 1049.9310, 22.12445, 0.0),
> ['triadrecords'] = vector4(-829.0061, -698.2049, 28.0583, 291.2052),
> ['tuner'] = vector4(157.5888, -3017.9968, 7.0400, 94.0695),
> ['vu'] = vector4(129.4555, -1299.6754, 29.2327, 27.6378),
> 
> -- Patoche
> ['luxerydealership'] = vector4(-1273.22, -371.11, 36.64, 301.8),
> 
> -- Unclejust
> ['digitalden'] = vector4(-656.28, -849.92, 24.51, 167.42),
> ['ifruitstore1'] = vector4(-646.78, -288.17, 35.49, 297.73),
> ['ifruitstore2'] = vector4(-778.7451, -598.2717, 30.2772, 181.0197),
> ['taxijob'] = vector4(908.7, -166.45, 74.13, 54.88),
> ['vineyard'] = vector4(-1892.29, 2038.47, 140.86, 339.23),
> ['weazelnews'] = vector4(-604.82, -933.22, 23.86, 292.3),
> ```
> 
> }

I had to put an older copy in, due to its the locals that's having the issues same as other scripts

**Comment by MinimumVK** [comment]
> I'm not sure what's going on with this new qb-management system but boss menu will not open,
> 
> "Update" Figured out why bossmenu not showing. they used the vectors for the location on custom mlo's and not the default map.
> 
> Almost all the boss locations are not set to default locations which makes it a pain if you want qb-target turned on, Why in the hell wouldn't the vectors be setup for default map locations and not custom maps not provided? some of the custom mlo that is being used is paid mlo's.
> 
> I'm not closing this out even though it's not a bug because the scripter never mentions anywhere that you need custom mlo's to find the boss menu.
> 
> the way I found the bossmenu is I went into noclip mode then use the vector to tp from the /tp cords and sure enough over more than half the bossmenu is hidden in default building above or below ground.
> 
> Under the qbcore/shared/locations folder they have actually listed the custom Mlo's that has some of the bossmenu placed at And under qb-management/client/custom shows the vectors for these custom mlo.
> 
> Luckily for me I have the custom mlo's and the locations folder did help me know which ones to install, However this is a very serious issue for people who don't mess with visual studio or codes. Esp when no guidance was provided from the script makers about these and other issues.
> 
> "As it stands this is not a working basic server setup with half of the scripts you need for a functional server based off of custom mlo's"
> 
> example of finding bossmenu under mechanic job with fresh install of Qbcore server with TXadmin recipe. https://imgur.com/vvay6iZ https://imgur.com/91y36Nr
> 
> -- Unknown/Random/Vanilla ['burgershot'] = vector4(-1199.0568, -882.4495, 13.3500, 209.1105), ['casino'] = vector4(923.2289, 47.3113, 81.1063, 237.6052),
> 
> ```
> -- Gabz
> ['arcade'] = vector4(-1649.6089, -1083.9313, 13.1575, 46.4121),
> ['beanmachinelegion'] = vector4(116.16, -1022.99, 29.3, 0.0),
> ['bowling'] = vector4(761.5008, -777.7256, 26.3078, 90.5581),
> ['pizzaria'] = vector4(790.4561, -758.4601, 26.7424, 270.2329),
> ['catcafe'] = vector4(-580.8388, -1072.7872, 22.3296, 359.0078),
> ['carmeet'] = vector4(958.8237, -1699.6659, 29.5574, 71.2731),
> ['davispd'] = vector4(382.5791, -1591.1827, 29.2828, 145.0991),
> ['popsdiner'] = vector4(1595.9753, 6448.6421, 25.3170, 28.3026),
> ['davisfirestation'] = vector4(216.7576, -1638.3801, 29.5151, 137.8174),
> ['harmony'] = vector4(1183.0693, 2648.5313, 37.8363, 194.0603),
> ['haters'] = vector4(-1117.1525, -1439.4297, 5.1075, 103.4411),
> ['hayes'] = vector4(-1435.7040, -445.7360, 35.5964, 220.1762),
> ['pdm'] = vector4(-48.2113, -1105.4769, 27.2634, 339.5899),
> ['bennys'] = vector4(-47.5289, -1042.6086, 28.3532, 247.9748),
> ['impound'] = vector4(-190.5874, -1156.1343, 23.0482, 158.9385),
> ['lamesaauto'] = vector4(720.4776, -1092.1934, 22.2866, 310.1469),
> ['lamesapd'] = vector4(824.3735, -1290.0670, 28.2364, 266.1293),
> ['lostmc'] = vector4(982.6339, -104.7095, 74.8488, 30.8738),
> ['pillbox'] = vector4(298.1153, -584.2825, 43.2609, 252.7553),
> ['mrpd'] = vector4(432.0686, -981.6853, 30.7119, 267.3501),
> ['mirrorparkhouse1'] = vector4(945.9535, -652.9119, 58.0228, 90.5541),
> ['pacificbank'] = vector4(229.9529, 214.3890, 105.5561, 294.6791),
> ['paletoliquor'] = vector4(-154.2287, 6328.8682, 31.5665, 133.1992),
> ['paletopd'] = vector4(-436.0935, 6015.2026, 31.4892, 132.9752),
> ['paletogasstation'] = vector4(120.2420, 6625.4722, 31.9580, 36.5687),
> ['pinkcage'] = vector4(323.9055, -203.2524, 54.0866, 186.8505),
> ['ponsonbys1'] = vector4(-165.2497, -304.3988, 38.07126, 0.0),
> ['ponsonbys2'] = vector4(-1448.1, -236.8420, 48.15098, 0.0),
> ['ponsonbys3'] = vector4(-709.8120, -150.6267, 35.75312, 0.0),
> ['prison'] = vector4(1847.1284, 2586.0696, 45.6726, 91.7828),
> ['rangerstation'] = vector4(387.3204, 790.1508, 187.6927, 4.7656),
> ['recordastudio'] = vector4(473.3006, -109.4360, 62.7418, 350.8488),
> ['sandypd'] = vector4(1839.7510, 3667.9907, 33.8787, 29.1744),
> ['suburban1'] = vector4(124.9756, -217.6290, 55.81879, 0.0),
> ['suburban2'] = vector4(617.4776, 2757.4810, 43.34935, 0.0),
> ['suburban3'] = vector4(-1195.8690, -773.5746, 18.58485, 0.0),
> ['suburban4'] = vector4(-3170.9670, 1049.9310, 22.12445, 0.0),
> ['triadrecords'] = vector4(-829.0061, -698.2049, 28.0583, 291.2052),
> ['tuner'] = vector4(157.5888, -3017.9968, 7.0400, 94.0695),
> ['vu'] = vector4(129.4555, -1299.6754, 29.2327, 27.6378),
> 
> -- Patoche
> ['luxerydealership'] = vector4(-1273.22, -371.11, 36.64, 301.8),
> 
> -- Unclejust
> ['digitalden'] = vector4(-656.28, -849.92, 24.51, 167.42),
> ['ifruitstore1'] = vector4(-646.78, -288.17, 35.49, 297.73),
> ['ifruitstore2'] = vector4(-778.7451, -598.2717, 30.2772, 181.0197),
> ['taxijob'] = vector4(908.7, -166.45, 74.13, 54.88),
> ['vineyard'] = vector4(-1892.29, 2038.47, 140.86, 339.23),
> ['weazelnews'] = vector4(-604.82, -933.22, 23.86, 292.3),
> ```
> 
> }

Do you know why the boss menu isn't showing up? I edited the vector3 coords but they dont show up!

**Comment by Soldierofthelam** [comment]
> Do you know why the boss menu isn't showing up? I edited the vector3 coords but they dont show up!

If you changed the coords and have QBtarget set to on in the server.cfg file you need to set new polyzones for those coords

Turning off the qb-target should allow you to use changed vectors

"Server.cfg"
# QBCore UseTarget
setr UseTarget false

**Comment by Rtextbook** [comment]
it does function properly when setr use target false.. but what if we want to use target how do you make it show itself then..
