### ISSUE TITLE
Config edited vector3

### ISSUE THREAD

**Issue by MinimumVK** [qbcore-framework/qb-management#82]
So today i have updated the script. I went into the config to edit the vector3 coords for the default MLO. In-game i copied vector3 and then pasted it into the config. I saved the file, restarted the server but the target just doesn't show up!

**Comment by sinphoenix** [comment]
you have to set poly for it to be 3rd eye

**Comment by singh-manavv** [comment]
You need to create a poly zone , in order to use qb-target (3rd eye).

**Comment by singh-manavv** [comment]
This isn't an issue , so we will be closing this thread.
