### ISSUE TITLE
[BUG] SQL Error 1062 when trying to run SQL in HeidiSQL

### ISSUE THREAD

**Issue by Tonyh194** [qbcore-framework/qb-management#83]
I downloaded QB-Management script today and when I try to run the SQL i'm constantly running into this error and have no idea on how to fix this. 
Any tips?
![image](https://user-images.githubusercontent.com/121644975/210018693-41d553bd-d89f-4b59-8949-8915a60e7a81.png)

**Comment by sinphoenix** [comment]
its saying that is already in your database
