### ISSUE TITLE
QB-managment gang/boss menu

### ISSUE THREAD

**Issue by OBDre** [qbcore-framework/qb-management#84]
have gone into the configs and add a gang menu but doesn't show up for the boss i've even read the read.me and video on how to set it up but still doesn't come up

**Comment by HawkEye172** [comment]
> have gone into the configs and add a gang menu but doesn't show up for the boss i've even read the read.me and video on how to set it up but still doesn't come up

Hey do u still need help with this?

**Comment by Wacksum9** [comment]
> > have gone into the configs and add a gang menu but doesn't show up for the boss i've even read the read.me and video on how to set it up but still doesn't come up
> 
> Hey do u still need help with this?

i do

**Comment by OBDre** [comment]
> > have gone into the configs and add a gang menu but doesn't show up for the boss i've even read the read.me and video on how to set it up but still doesn't come up
> 
> Hey do u still need help with this?

yes

**Comment by sinphoenix** [comment]
Still having this issue?

**Comment by DopeLovingHippy** [comment]
did you find a fix
