### ISSUE TITLE
Qb-managment not Working [BUG] 

### ISSUE THREAD

**Issue by Wacksum9** [qbcore-framework/qb-management#85]
![20230124225029_1](https://user-images.githubusercontent.com/121142535/214476119-163bccfc-0083-443f-99e9-58cdd7de4a3c.jpg)
anyone know how to fix?

**Comment by singh-manavv** [comment]
It seems you have somehow removed the import of qbcore core object from the top of script because of which the resource is unable to find the core object and hence giving this error. 

This isn't an issue from our side , so we will be closing this thread.
