### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by ZroIsHere** [qbcore-framework/qb-management#86]
Translate to spanish

local Translations = {
    headers = {
        ['bsm'] = 'Menu del jefe - ',
    },
    body = {
        ['manage'] = 'Administrar empleados',
        ['managed'] = 'Ver tu lista de empleados',
        ['hire'] = 'Contratar empleado',
        ['hired'] = 'Contratar empleado cercano',
        ['storage'] = 'Acceso al almacén',
        ['storaged'] = 'Abrir almacén',
        ['outfits'] = 'Conjuntos de ropa',
        ['outfitsd'] = 'Cambiar conjunto de ropa',
        ['money'] = 'Administración del dinero',
        ['moneyd'] = 'Ver dinero de la compañía',
        ['mempl'] = 'Administrar empleados - ',
        ['mngpl'] = 'Administrar ',
        ['grade'] = 'Grado: ',
        ['fireemp'] = 'Despedir empleado',
        ['hireemp'] = 'Contratar empleados - ',
        ['cid'] = 'DNI: ',
        ['balance'] = 'Dinero: ',
        ['deposit'] = 'Depositar',
        ['depositd'] = 'Depositar dinero en la cuenta',
        ['withdraw'] = 'Retirar',
        ['withdrawd'] = 'Retirar dinero de la cuenta',
        ['depositm'] = 'Depositar dinero <br> Dinero disponible: ',
        ['withdrawm'] = 'Retirar dinero <br> Dinero disponible: ',
        ['submit'] = 'Confirmar',
        ['amount'] = 'Cantidad',
        ['return'] = 'Volver',
        ['exit'] = 'Salir',
    },
    drawtext = {
        ['label'] = '[E] Abrir menu del jefe',
    },
    target = {
        ['label'] = 'Menu del jefe',
    },
    headersgang = {
        ['bsm'] = 'Administración de banda  - ',
    },
    bodygang = {
        ['manage'] = 'Administrar miembros de banda',
        ['managed'] = 'Ver tu lista de miembros',
        ['hire'] = 'Reclutar miembros',
        ['hired'] = 'Reclutar miembros cercanos',
        ['storage'] = 'Acceso al almacén',
        ['storaged'] = 'Abrir almacén de banda',
        ['outfits'] = 'Conjuntos de ropa',
        ['outfitsd'] = 'Cambiar conjunto de ropa',
        ['money'] = 'Administración del dinero',
        ['moneyd'] = 'Ver dinero de la banda',
        ['mempl'] = 'Administrar miembros de la banda - ',
        ['mngpl'] = 'Administrar ',
        ['grade'] = 'Grado: ',
        ['fireemp'] = 'Echar de la banda',
        ['hireemp'] = 'Reclutar miembros para la banda - ',
        ['cid'] = 'DNI: ',
        ['balance'] = 'Dinero: ',
        ['deposit'] = 'Depositar',
        ['depositd'] = 'Depositar dinero en la cuenta',
        ['withdraw'] = 'Retirar',
        ['withdrawd'] = 'Retirar dinero de la cuenta',
        ['depositm'] = 'Depositar dinero <br> Dinero disponible: ',
        ['withdrawm'] = 'Retirar dinero <br> Dinero disponible: ',
        ['submit'] = 'Confirmar',
        ['amount'] = 'Cantidad',
        ['return'] = 'Volver',
        ['exit'] = 'Salir',
    },
    drawtextgang = {
        ['label'] = '[E] Abrir menu de banda',
    },
    targetgang = {
        ['label'] = 'Menu de banda',
    }
}

Lang = Lang or Locale:new({
    phrases = Translations,
    warnOnMissing = true
})

**Comment by sinphoenix** [comment]
put in pull request for Spanish TR for loc.
