### ISSUE TITLE
qb-management showing ever person in server in a gang [BUG]

### ISSUE THREAD

**Issue by beyond420** [qbcore-framework/qb-management#93]
**Describe the bug**
on QB-management i have made 2 gangs. now with those gangs you can go into the boss menu lets says and see every single person in the city even if there not online. also other gangs can fire someone from the other gang because it shows all gang members in the city/plus all non gang members. does anyone know a fix for this? or has anyone else experienced this and know what to do? i dont want all the gangs able to control other gangs stuff. they cant recruit new members because it thinks all the members in the city are part of the gang. im not getting any errors anywhere.

**To Reproduce**
1. Go to 'in gang boss menu for gangs'
2. Click on 'management gang members'
3. Use this item 'click the manage gang member it shows everyone in the city and you can manage other gangs people also' (item's name from shared.lua if applicable)

**Expected behavior**
i expect all the gangs to be able to have there own gangs and stuff. be able to control there own boss menu and hire/fire people for only that gang there in. im not getting any errors on anything server side or client side.

**Screenshots**

**Questions (please complete the following information):**
i have the newest management update and newest qb-menu
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no i have not renamed anything with the file

**Additional context**

**Comment by sinphoenix** [comment]
Still an issue?  i could not get this to happen.. if its still an issue update to the latest version and let me know
